/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-background',
    'bg-surface',
    'bg-surface-elevated',
    'border-border',
    'text-primary',
    'text-text',
    'text-text-secondary',
    'text-text-muted',
    'bg-primary',
    'bg-primary-hover',
    'bg-success',
    'bg-error',
    'bg-warning',
    'text-background',
    'hover:bg-border',
    'focus:border-primary',
    'text-error',
    'border-error',
    'border-success',
    // Role badge colors
    'bg-warning/20',
    'text-warning',
    'border-warning',
    'bg-primary/20',
    'border-primary',
    'bg-text-secondary/20',
    'border-border',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0a0a0f',
        surface: '#12121a',
        'surface-elevated': '#1e1e2e',
        border: '#2a2a3a',
        primary: '#4fc3f7',
        'primary-hover': '#29b6f6',
        accent: '#00e5ff',
        success: '#69f0ae',
        warning: '#ffd740',
        error: '#ff5252',
        member: '#aaaaaa',
        text: '#e0e0e0',
        'text-secondary': '#888888',
        'text-muted': '#555555',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
}
