"""initial_schema

Revision ID: 7a893c2cfed5
Revises: 
Create Date: 2026-06-14 23:11:01.440270
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('is_display_active', sa.Boolean(), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('last_rate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_source', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'code', name='uq_currencies_household_id_code')
    )
    op.create_table('fx_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_secret_ref', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('household_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('picture_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_currency', sa.String(length=3), nullable=False),
    sa.Column('default_view', sa.String(length=20), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('can_create_household', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('colour', sa.String(length=7), nullable=True),
    sa.Column('font', sa.String(length=20), nullable=False),
    sa.Column('density', sa.String(length=20), nullable=False),
    sa.Column('reduce_motion', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', sa.Text(), nullable=True),
    sa.Column('dashboard_layout', sa.Text(), nullable=True),
    sa.Column('detachment_reason', sa.String(length=30), nullable=True),
    sa.Column('detached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_persons_household_id_email', ['household_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('approved_owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('category_type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint('depth <= 1', name='ck_categories_depth_max_1'),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_categories_household_id_parent_id', ['household_id', 'parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    op.create_table('entity_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'entity_type', 'entity_id', name='uq_entity_preferences_person_id_entity_type_entity_id')
    )
    with op.batch_alter_table('entity_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_entity_preferences_person_id_entity_type', ['person_id', 'entity_type'], unique=False)

    op.create_table('formulas',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('formula_key', sa.String(length=100), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('applies_to', sa.String(length=50), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'formula_key', name='uq_formulas_household_id_formula_key')
    )
    with op.batch_alter_table('formulas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formulas_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_formulas_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formulas_status'), ['status'], unique=False)

    op.create_table('fx_rate_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('currency_id', sa.String(length=36), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'rate_date', name='uq_fx_rate_history_currency_id_rate_date')
    )
    op.create_table('household_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('invited_email', sa.String(length=320), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('csrf_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csrf_token')
    )
    op.create_table('accounts',
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('colour', sa.String(length=7), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('depreciation_formula_id', sa.String(length=36), nullable=True),
    sa.Column('fx_formula_id', sa.String(length=36), nullable=True),
    sa.Column('interest_formula_id', sa.String(length=36), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('interest_frequency', sa.String(length=20), nullable=True),
    sa.Column('reserved_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reward_type', sa.String(length=20), nullable=True),
    sa.Column('bonus_limit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('points_expiry', sa.Date(), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('policy_no', sa.String(length=100), nullable=True),
    sa.Column('insurer', sa.String(length=200), nullable=True),
    sa.Column('policy_type', sa.String(length=20), nullable=True),
    sa.Column('policy_status', sa.String(length=20), nullable=True),
    sa.Column('premium_frequency', sa.String(length=20), nullable=True),
    sa.Column('coverage_death', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('coverage_tpd', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('coverage_ci', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('coverage_early_ci', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('coverage_personal_accident', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('coverage_hospital', sa.String(), nullable=True),
    sa.Column('surrender_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('surrender_inquiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['depreciation_formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['fx_formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['interest_formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_accounts_household_id_account_type', ['household_id', 'account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_status'), ['status'], unique=False)

    op.create_table('budgets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('owner_person_id', sa.String(length=36), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('limit_currency', sa.String(length=3), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('limit_amount_base', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('rollover', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_archived'), ['archived'], unique=False)
        batch_op.create_index('ix_budgets_category_id_period_start', ['category_id', 'period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_budgets_household_id_period_start_end', ['household_id', 'period_start', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_status'), ['status'], unique=False)

    op.create_table('account_owners',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'person_id')
    )
    op.create_table('account_snapshots',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('value_base', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('formula_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_account_snapshots_account_id_snapshot_date', ['account_id', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshots_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshots_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshots_status'), ['status'], unique=False)

    op.create_table('financial_events',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('transaction_status', sa.String(length=20), nullable=False),
    sa.Column('payee_person_id', sa.String(length=36), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('is_shared_expense', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_gst_claimable', sa.Boolean(), nullable=False),
    sa.Column('is_gift', sa.Boolean(), nullable=False),
    sa.Column('source_account_id', sa.String(length=36), nullable=True),
    sa.Column('linked_recurring_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('frequency_text', sa.String(length=50), nullable=True),
    sa.Column('frequency_rule', sa.Text(), nullable=True),
    sa.Column('next_occurrence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_start_date', sa.Date(), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('source_entity_type', sa.String(length=30), nullable=True),
    sa.Column('source_entity_id', sa.String(length=36), nullable=True),
    sa.Column('occurrences_generated', sa.Integer(), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_account_id', sa.String(length=36), nullable=True),
    sa.Column('dest_currency', sa.String(length=3), nullable=True),
    sa.Column('dest_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('dest_amount_base', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('is_debt_repayment', sa.Boolean(), nullable=True),
    sa.Column('debt_cleared_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('amount_base_calculated', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount_base', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('fx_delta', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.CheckConstraint("is_shared_expense = 0 OR transaction_type = 'outflow'", name='ck_shared_expense_outflow_only'),
    sa.ForeignKeyConstraint(['archived_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['linked_recurring_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['payee_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_events', schema=None) as batch_op:
        batch_op.create_index('ix_fe_household_id_category_id', ['household_id', 'category_id'], unique=False)
        batch_op.create_index('ix_fe_household_id_event_date', ['household_id', 'event_date'], unique=False)
        batch_op.create_index('ix_fe_household_id_payee_person_id', ['household_id', 'payee_person_id'], unique=False)
        batch_op.create_index('ix_fe_household_id_shared_expense_type', ['household_id', 'is_shared_expense', 'transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_events_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_events_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_events_status'), ['status'], unique=False)

    op.create_table('occurrence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recurring_event_id', sa.String(length=36), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('occurrence_status', sa.String(length=20), nullable=False),
    sa.Column('generated_event_id', sa.String(length=36), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_event_id'], ['financial_events.id'], ),
    sa.ForeignKeyConstraint(['recurring_event_id'], ['financial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occurrence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrence_records_recurring_event_id'), ['recurring_event_id'], unique=False)
        batch_op.create_index('ix_occurrence_records_recurring_event_id_expected_date', ['recurring_event_id', 'expected_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_records', schema=None) as batch_op:
        batch_op.drop_index('ix_occurrence_records_recurring_event_id_expected_date')
        batch_op.drop_index(batch_op.f('ix_occurrence_records_recurring_event_id'))

    op.drop_table('occurrence_records')
    with op.batch_alter_table('financial_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_events_status'))
        batch_op.drop_index(batch_op.f('ix_financial_events_household_id'))
        batch_op.drop_index(batch_op.f('ix_financial_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_financial_events_archived'))
        batch_op.drop_index('ix_fe_household_id_shared_expense_type')
        batch_op.drop_index('ix_fe_household_id_payee_person_id')
        batch_op.drop_index('ix_fe_household_id_event_date')
        batch_op.drop_index('ix_fe_household_id_category_id')

    op.drop_table('financial_events')
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_snapshots_status'))
        batch_op.drop_index(batch_op.f('ix_account_snapshots_household_id'))
        batch_op.drop_index(batch_op.f('ix_account_snapshots_archived'))
        batch_op.drop_index('ix_account_snapshots_account_id_snapshot_date')
        batch_op.drop_index(batch_op.f('ix_account_snapshots_account_id'))

    op.drop_table('account_snapshots')
    op.drop_table('account_owners')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_status'))
        batch_op.drop_index('ix_budgets_household_id_period_start_end')
        batch_op.drop_index(batch_op.f('ix_budgets_household_id'))
        batch_op.drop_index('ix_budgets_category_id_period_start')
        batch_op.drop_index(batch_op.f('ix_budgets_archived'))

    op.drop_table('budgets')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_status'))
        batch_op.drop_index('ix_accounts_household_id_account_type')
        batch_op.drop_index(batch_op.f('ix_accounts_household_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_archived'))

    op.drop_table('accounts')
    op.drop_table('sessions')
    op.drop_table('household_invitations')
    op.drop_table('fx_rate_history')
    with op.batch_alter_table('formulas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formulas_status'))
        batch_op.drop_index(batch_op.f('ix_formulas_household_id'))
        batch_op.drop_index(batch_op.f('ix_formulas_archived'))

    op.drop_table('formulas')
    with op.batch_alter_table('entity_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_preferences_person_id_entity_type')

    op.drop_table('entity_preferences')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))
        batch_op.drop_index('ix_categories_household_id_parent_id')
        batch_op.drop_index(batch_op.f('ix_categories_household_id'))
        batch_op.drop_index(batch_op.f('ix_categories_archived'))

    op.drop_table('categories')
    op.drop_table('approved_owners')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_household_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_archived'))

    op.drop_table('alerts')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_status'))
        batch_op.drop_index('ix_persons_household_id_email')
        batch_op.drop_index(batch_op.f('ix_persons_household_id'))
        batch_op.drop_index(batch_op.f('ix_persons_archived'))

    op.drop_table('persons')
    op.drop_table('fx_providers')
    op.drop_table('currencies')
    op.drop_table('households')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_household_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
