"""add_can_create_household_to_persons

Revision ID: 4348438110ec
Revises: 478b9aab235f
Create Date: 2026-06-07 17:46:46.725370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4348438110ec'
down_revision: Union[str, Sequence[str], None] = '478b9aab235f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_household', sa.Boolean(), server_default='false', nullable=False))

    # Backfill: existing owners already have a household, grant them the right
    op.execute("UPDATE persons SET can_create_household = true WHERE role = 'owner'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('can_create_household')

    # ### end Alembic commands ###
