"""make_persons_household_id_nullable

Revision ID: a2064ba6d028
Revises: 4957ef973a94
Create Date: 2026-06-04 00:09:28.389377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2064ba6d028'
down_revision: Union[str, Sequence[str], None] = '4957ef973a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.alter_column('household_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('household_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
